Linux 3.18.16
commit 14c0c571cf48b0139ea44ca34274813a164e55f3
Author: Sasha Levin <sasha.levin@oracle.com>
Date:   Sun Jun 14 12:19:31 2015 -0400

    Linux 3.18.16

    Signed-off-by: Sasha Levin <sasha.levin@oracle.com>

commit ac6966f264ee7fd6b3b269b8e3e2ea6af5a83f24
Author: Andrew Morton <akpm@linux-foundation.org>
Date:   Wed Jun 10 11:15:02 2015 -0700

    arch/x86/kvm/mmu.c: work around gcc-4.4.4 bug

    [ Upstream commit 5ec45a192fe6e287f0fc06d5ca4f3bd446d94803 ]

    Fix this compile issue with gcc-4.4.4:

       arch/x86/kvm/mmu.c: In function 'kvm_mmu_pte_write':
       arch/x86/kvm/mmu.c:4256: error: unknown field 'cr0_wp' specified in initializer
       arch/x86/kvm/mmu.c:4257: error: unknown field 'cr4_pae' specified in initializer
       arch/x86/kvm/mmu.c:4257: warning: excess elements in union initializer
       ...

    gcc-4.4.4 (at least) has issues when using anonymous unions in
    initializers.

    Fixes: edc90b7dc4ceef6 ("KVM: MMU: fix SMAP virtualization")
    Cc: Xiao Guangrong <guangrong.xiao@linux.intel.com>
    Cc: Paolo Bonzini <pbonzini@redhat.com>
    Cc: Davidlohr Bueso <dave@stgolabs.net>
    Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
    Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
    Signed-off-by: Sasha Levin <sasha.levin@oracle.com>

commit b6e707234177f28b64fb411993190073c6099b54
Author: Eric Work <work.eric@gmail.com>
Date:   Mon May 18 23:26:23 2015 -0700

    md/raid0: fix restore to sector variable in raid0_make_request

    [ Upstream commit a81157768a00e8cf8a7b43b5ea5cac931262374f ]

    The variable "sector" in "raid0_make_request()" was improperly updated
    by a call to "sector_div()" which modifies its first argument in place.
    Commit 47d68979cc968535cb87f3e5f2e6a3533ea48fbd restored this variable
    after the call for later re-use.  Unfortunetly the restore was done after
    the referenced variable "bio" was advanced.  This lead to the original
    value and the restored value being different.  Here we move this line to
    the proper place.

    One observed side effect of this bug was discarding a file though
    unlinking would cause an unrelated file's contents to be discarded.

    Signed-off-by: NeilBrown <neilb@suse.de>
    Fixes: 47d68979cc96 ("md/raid0: fix bug with chunksize not a power of 2.")
    Cc: stable@vger.kernel.org (any that received above backport)
    URL: https://bugzilla.kernel.org/show_bug.cgi?id=98501
    Signed-off-by: Sasha Levin <sasha.levin@oracle.com>